import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={inter.className}>
      <body className='flex flex-col'>
        <Header />
        <main className='grow w-full max-w-6xl mx-auto px-3 py-4'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
